{% set version = "0.7" %}

package:
  name: dcmstack
  version: {{ version }}

source:
  fn: dcmstack-{{ version }}.tar.gz
  url: https://github.com/moloney/dcmstack/archive/v{{ version }}.tar.gz
  md5: 34fea448a122bca5ae3234286f15308a

build:
  number: 1000
  skip: true  # [py3k]
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools
    - nibabel
  run:
    - python
    - pydicom
    - nibabel

test:
  imports:
    - dcmstack

about:
  home: http://dcmstack.readthedocs.io/
  license: MIT
  summary: This package provides DICOM to Nifti conversion with the added ability to extract and summarize meta data from the source DICOMs.

extra:
  recipe-maintainers:
    - arokem
