{% set name = "dcmstack" %}
{% set version = "0.9.0" %}
{% set python_min = "3.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/dcmstack-{{ version }}.tar.gz
  sha256: 9e131226fb00cdc72f5c2ad61f82b37020d3f97f272d1becb880168bd4504860

build:
  number: 0
  noarch: python
  entry_points:
    - dcmstack = dcmstack.dcmstack_cli:main
    - nitool = dcmstack.nitool_cli:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
    - numpy <2.0
  run:
    - nibabel >=2.1.0
    - nibabel <4.0a0
    - pydicom >=0.9.7
    - python >={{ python_min }}
    - pylibjpeg-libjpeg >=2.3.0
    - numpy <2.0

test:
  imports:
    - dcmstack
  commands:
    - pip check
    - dcmstack --help
    - nitool --help
  requires:
    - python {{ python_min }}
    - pip

about:
  home: http://dcmstack.readthedocs.io/
  license: MIT
  license_file: COPYING
  summary: This package provides DICOM to Nifti conversion with the added ability to extract and summarize meta data from the source DICOMs.

extra:
  recipe-maintainers:
    - arokem
    - kastman
