{% set name = "dcmstack" %}
{% set version = "0.8.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/dcmstack-{{ version }}.tar.gz
  sha256: 12ea9851c18d5196104e57d412f7d27f6f3942ecdce3db488cba95fc26abff04

build:
  number: 4
  noarch: python
  entry_points:
    - dcmstack = dcmstack.dcmstack_cli:main
    - nitool = dcmstack.nitool_cli:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - nibabel >=2.1.0
    - nibabel <4.0a0
    - pydicom >=0.9.7
    - python >={{ python_min }}

test:
  imports:
    - dcmstack
  commands:
    - pip check
    - dcmstack --help
    - nitool --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: http://dcmstack.readthedocs.io/
  license: MIT
  license_file: COPYING
  summary: This package provides DICOM to Nifti conversion with the added ability to extract and summarize meta data from the source DICOMs.

extra:
  recipe-maintainers:
    - arokem
    - kastman
