{% set version = "0.8" %}

package:
  name: dcmstack
  version: {{ version }}

source:
  fn: dcmstack-{{ version }}.tar.gz
  url: https://github.com/moloney/dcmstack/archive/v{{ version }}.tar.gz
  sha256: b879e1cb30a7d761476b79d11627b76d937a2637799fae6afb4c0317a42d639e

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools
    - nibabel
  run:
    - python
    - pydicom
    - nibabel

test:
  imports:
    - dcmstack

about:
  home: http://dcmstack.readthedocs.io/
  license: MIT
  license_file: COPYING
  summary: This package provides DICOM to Nifti conversion with the added ability to extract and summarize meta data from the source DICOMs.

extra:
  recipe-maintainers:
    - arokem
    - kastman
