{% set version = "0.8" %}

package:
  name: dcmstack
  version: {{ version }}

source:
  fn: dcmstack-{{ version }}.tar.gz
  url: https://codeload.github.com/moloney/dcmstack/archive/v{{ version }}.tar.gz
  md5: d500c76f73737c13c5729f87649e4892

build:
  number: 0
  skip: true  # [py3k]
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools
    - nibabel
  run:
    - python
    - pydicom
    - nibabel

test:
  imports:
    - dcmstack

about:
  home: http://dcmstack.readthedocs.io/
  license: MIT
  license_file: COPYING
  summary: This package provides DICOM to Nifti conversion with the added ability to extract and summarize meta data from the source DICOMs.

extra:
  recipe-maintainers:
    - arokem
