# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_python2.7

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "orZQcMBjBwCp37rWbDhAmbade4mxM7+zwlqcEBJbFiSVJPaaVv8UtMbSwJEZLF7wYaXakX4OqKuFNjbSk3kBnMVKdjgyebNPeDKrUAdd4xV2tTzgTXfqQpha8fRVnxmgBUQSRA2eTNx/53G7BR/ASr2QQjMBVNyTS7jS8Lfqv/2/vKMxSGOgXZ6GVwikKAYIeabfJT01B+L4XUj87GOspCiGQ/ZfDJNBmMBLPPakGGOfp+QIQZ8GPRfIVMNl8HcoDmiiXQP9o1lqhRSdIGujlXKxV9INQMIerBKZ2syMtpsGAHDIjpdpUwm7qNttBPz5UvDkxstEw8TKnLg2Eq2qylLQ28vtw69AdvBKwXBAojhn6XuZ0GYbG0WkVjSG+PX4sxfbxE0FiMfGtTScnpjV3LsiZVabhgCgrjfY7jS3nShYYS/8Dwl9lZ866yqLQgZmEZ+RzgndP+zgF+OYVSAjr0lPdNkQWgGWeACzw0dNAnS3NLonNHwf1pltAZG6/N3/7FWRjNokA3DwVF6txRbR2/+Pz8eLQpkU8cRzpYBwPJm4oiAywK6Zq7VLr9R3EOZ7H8QKFEvDya5oTaL3fk8+nh28ThRjU1gIjIoJDy46JycktVfZauYVyeeuHYIjJrOQQ/psSk5EzipFHlGmhoo5iYVTHrEg/jZOjgl9bCzQl2Q="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install --yes --quiet conda-forge::conda-forge-ci-setup=2
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml
