appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: orZQcMBjBwCp37rWbDhAmbade4mxM7+zwlqcEBJbFiSVJPaaVv8UtMbSwJEZLF7wYaXakX4OqKuFNjbSk3kBnMVKdjgyebNPeDKrUAdd4xV2tTzgTXfqQpha8fRVnxmgBUQSRA2eTNx/53G7BR/ASr2QQjMBVNyTS7jS8Lfqv/2/vKMxSGOgXZ6GVwikKAYIeabfJT01B+L4XUj87GOspCiGQ/ZfDJNBmMBLPPakGGOfp+QIQZ8GPRfIVMNl8HcoDmiiXQP9o1lqhRSdIGujlXKxV9INQMIerBKZ2syMtpsGAHDIjpdpUwm7qNttBPz5UvDkxstEw8TKnLg2Eq2qylLQ28vtw69AdvBKwXBAojhn6XuZ0GYbG0WkVjSG+PX4sxfbxE0FiMfGtTScnpjV3LsiZVabhgCgrjfY7jS3nShYYS/8Dwl9lZ866yqLQgZmEZ+RzgndP+zgF+OYVSAjr0lPdNkQWgGWeACzw0dNAnS3NLonNHwf1pltAZG6/N3/7FWRjNokA3DwVF6txRbR2/+Pz8eLQpkU8cRzpYBwPJm4oiAywK6Zq7VLr9R3EOZ7H8QKFEvDya5oTaL3fk8+nh28ThRjU1gIjIoJDy46JycktVfZauYVyeeuHYIjJrOQQ/psSk5EzipFHlGmhoo5iYVTHrEg/jZOjgl9bCzQl2Q=}
provider:
  win: azure
  osx: azure
  linux: azure
