travis:
  secure:
    BINSTAR_TOKEN: n51/QmWOlUpynYiq/NhXMrlqKC1e7Ea41YG8F20kW/oyVS74etJO2nbqhAOs4k6akgwY1JjKc89XgGcGCs3UL/s/ByZxhysDUDVtfqDNP/W0B/JL5jExx8IANi0bZ/DI5Ocs+0crIzEug+p777LFUr9WFlu7cD78dbqobnbJRVUsx7wN9Y4RMCXMVcNzfv5HHTWEHSNoJNDGzTgp9ig6FXdCC6bT8HXFqiyrXwhZjEMmfcFsfN9Pq/R4GffqG7Z9GpdSCgHvxq4fD4MjVeN3ZhKas8x+bzM3nAart9r98JaNTn1bIcxQgOfMDbJBmoeJyz/j+6kQeXsr+SiH+phRSQx7Dj+wz+HG8THXwaVLTkeXl/YJQ4b5NhYvi2RqNHqRbZU/c4sHaFxXj1ieyuuDx+ErhKnHT9oBzEdjzCG58ucy2HQ2qB8k7TxALNhU2a+UMKr1gWF19av60+VMF4K0f1GNHJKpKVuwvsjoUIJ2yKzbn84bc7VPlkOh1bX6LRa0Rsmx3f+fexLBEy3RRMSQ8yYDnRp0VNuNh52p7ZbbZpkP7cQfh4CTcmsA1hk3nqkLaMVMvKdLdRS5OvJfo24xtphpzab9yICEUhK9IwfvKTgA0KdgvcMqA8jt6gv9gmQYTRIo+GlqzaQPaH29Z8Cl5X6KA9/foGV8SlPcbRgpRYA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
